language: node_js
node_js:
  - 11

install:
  - npm install
  - cd ..
  - git clone https://github.com/LLK/scratch-gui.git
  - cd scratch-gui
  - git checkout scratch-desktop
  - npm install
  - BUILD_MODE=dist npm run build
  - npm link
  - cd ../scratch-desktop
  - npm link scratch-gui

script:
  - npm run build
  - PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g')

deploy:
  provider: releases
  api_key: "$API_KEY"
  file: "dist/Scratch Desktop $PACKAGE_VERSION.AppImage"
  ski_cleanup: true
